"""Deterministic, event-sourced execution contract shared by all market feeds."""

from qagent.execution.engine import (
    ExecutionResult,
    apply_market_event,
    apply_order_intent,
    cancel_order,
    expire_order,
    handle_order_intent,
    on_market_event,
    process_market_event,
    run_feed,
    run_market_feed,
    submit_order,
)
from qagent.execution.events import (
    EXECUTION_EVENT_ADAPTER,
    EventKind,
    ExecutionEvent,
    FillRecordedEvent,
    MarketEventProcessedEvent,
    OrderActivatedEvent,
    OrderCancelledEvent,
    OrderCreatedEvent,
    OrderExpiredEvent,
    OrderRejectedEvent,
    SessionAdvancedEvent,
    canonical_digest,
)
from qagent.execution.models import (
    OPEN_ORDER_STATUSES,
    TERMINAL_ORDER_STATUSES,
    AShareExecutionRules,
    Account,
    ExecutionState,
    FeeBreakdown,
    Fill,
    MarketEvent,
    Order,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    TimeInForce,
)
from qagent.execution.reducer import (
    ExecutionInvariantError,
    IdempotencyConflict,
    execution_reducer,
    reduce_event,
    reduce_events,
    replay_events,
)
from qagent.execution.rules import (
    apply_slippage,
    fee_breakdown,
    incremental_fee_breakdown,
    is_one_price_limit_blocked,
    is_tick_aligned,
    money,
    participation_capacity,
    price_limits,
    round_lot,
    round_to_tick,
)


AShareExecutionPolicy = AShareExecutionRules
replay = replay_events

__all__ = [
    "AShareExecutionPolicy",
    "AShareExecutionRules",
    "Account",
    "EXECUTION_EVENT_ADAPTER",
    "EventKind",
    "ExecutionEvent",
    "ExecutionInvariantError",
    "ExecutionResult",
    "ExecutionState",
    "FeeBreakdown",
    "Fill",
    "FillRecordedEvent",
    "IdempotencyConflict",
    "MarketEvent",
    "MarketEventProcessedEvent",
    "OPEN_ORDER_STATUSES",
    "Order",
    "OrderActivatedEvent",
    "OrderCancelledEvent",
    "OrderCreatedEvent",
    "OrderExpiredEvent",
    "OrderIntent",
    "OrderRejectedEvent",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "Position",
    "SessionAdvancedEvent",
    "TERMINAL_ORDER_STATUSES",
    "TimeInForce",
    "apply_market_event",
    "apply_order_intent",
    "apply_slippage",
    "cancel_order",
    "canonical_digest",
    "execution_reducer",
    "expire_order",
    "fee_breakdown",
    "handle_order_intent",
    "incremental_fee_breakdown",
    "is_one_price_limit_blocked",
    "is_tick_aligned",
    "money",
    "on_market_event",
    "participation_capacity",
    "price_limits",
    "process_market_event",
    "reduce_event",
    "reduce_events",
    "replay",
    "replay_events",
    "round_lot",
    "round_to_tick",
    "run_feed",
    "run_market_feed",
    "submit_order",
]
